config/routes.rb
Depot::Application.routes.draw do

  get "subclasses/create"

  get "subclasses/destroy"


  resources :types do  
    resources :subclasses  
  end  

  get "comments/create"

  get "comments/destroy"

  get 'admin' => 'admin#index'

  #get 'search'=> 'products#search'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :products do
    get 'search' => :search
  end

  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products do
	  resources :comments  

      get :who_bought, :on => :member
    end
    get 'search'=> 'products#search'
    root :to => 'store#index', :as => 'store'

  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body

  attr_accessible :order
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    
	  if current_item
      current_item.quantity += 1

	  else
		  current_item = line_items.build(product_id: product_id)
	  end 
	  current_item
  end 

  def total_price
    line_items.to_a.sum {|item| item.total_price }
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :product_id, :text
  belongs_to :product  

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base

  belongs_to :order
  belongs_to :product
  belongs_to :cart
  attr_accessible :cart_id, :product_id
  attr_accessible :product
  attr_accessible :quantity

  def total_price
    product.price * quantity
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :address, :email, :name, :pay_type, :time
  attr_accessible :cart, :product
  has_many :line_items, :dependent => :destroy
  PAYMENT_TYPES = [ "Check", "Credit card" , "Purchase order" ]
  validates :name, :address, :email, :pay_type, :presence => true
  validates :pay_type, :inclusion => PAYMENT_TYPES
  
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def total_price
    line_items.to_a.sum {|item| item.total_price }
  end
  
  def modify_product_stock_volumes(cart)
    cart.line_items.each do |item|
      #Product.find_by_title(item.title).stock_volumes -= item.quantity
      
    #  product = Product.find(:all,
     #   :conditions => " id = 'item.product_id'")
      if item 
        product = Product.find(item.product_id)
        product.stock_volumes -= item.quantity
        product.save
      end
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :comments  
  has_many :orders, :through => :line_items

  before_destroy :ensure_not_referenced_by_any_line_item
  
  attr_accessible :description, :image_url, :price, :title, :stock_volumes, :tags
  BOOK_TYPES = [ "IT", "math" ,"subclass11","subclass12","subclass13","subclass14",
                "subclass21","subclass22","subclass23","subclass24","subclass25",
                "subclass31","subclass32","subclass33","subclass34","subclass35",
                "subclass41","subclass42","subclass43","subclass44","subclass45"]
  validates :title, :description, :image_url, :stock_volumes, :tags, presence: true
  validates :tags, :inclusion => BOOK_TYPES
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)$}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }
  private
	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
			return true
		else
			errors.add(:base, 'Line Items present')
			return false
		end
	end
end

app/models/subclass.rb
class Subclass < ActiveRecord::Base
  attr_accessible :content, :type_id  
  belongs_to :type
end

app/models/type.rb
class Type < ActiveRecord::Base
  attr_accessible :type_name, :content
  has_many :subclasses
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password_digest, :password, :password_confirmation
  validate :name, presence: true, uniqueness: true
  has_secure_password
  after_destroy :ensure_an_admin_remains
  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  #before_filter :authorize
  def index
    @total_orders = Order.count
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json
  skip_before_filter :authorize, only: [:create, :update, :destroy]
  
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attemp to access invalid cart #{params[:id]}"
      redirect_to store_url, notice: 'Invalid cart'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @cart }
      end
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
  #  @cart = Cart.find(params[:id])
    @cart = current_cart
    @cart.destroy
    
    session[:cart_id] =  nil

    respond_to do |format|
      format.html { redirect_to store_url}  
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def hidden_div_if(condition, attributes={}, &block)
    if condition
      attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)

  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/subclass_helper.rb
module SubclassHelper
end

app/helpers/subclasses_helper.rb
module SubclassesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_cart.html.erb
<div class="cart_title">Your Cart</div>
<table>
	<%= render(cart.line_items) %>

	<tr class="total_line">
		
		<td colspan="2">Total</td>
		<td class="total_cell"><%= number_to_currency(cart.total_price)%></td>
	</tr>
</table>
<%= button_to t('.checkout'), new_order_path, method: :get %>
<%= button_to t('.empty'), cart, method: :delete,
	confirm: 'Are you sure?'%>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<%= stylesheet_link_tag    "carts" %> 
<%= javascript_include_tag "carts" %>
<%= csrf_meta_tags %>

<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<div class="cart_title">Your Pragmatic Cart</div>
<table>
	<%= render(@cart.line_items) %>
	
	<tr class="total_line">
		<td colspan="2">Total</td>
		<td class="total_cell"><%= number_to_currency(@cart.total_price)%></td>
	</tr>
</table>

<%= button_to 'Empty cart', @cart, method: :delete,
	confirm: 'Are you sure?'%>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>