config/routes.rb
Depot::Application.routes.draw do

  get "subclasses/create"

  get "subclasses/destroy"


  resources :types do  
    resources :subclasses  
  end  

  get "comments/create"

  get "comments/destroy"

  get 'admin' => 'admin#index'

  #get 'search'=> 'products#search'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :products do
    get 'search' => :search
  end

  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products do
	  resources :comments  

      get :who_bought, :on => :member
    end
    get 'search'=> 'products#search'
    root :to => 'store#index', :as => 'store'

  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body

  attr_accessible :order
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    
	  if current_item
      current_item.quantity += 1

	  else
		  current_item = line_items.build(product_id: product_id)
	  end 
	  current_item
  end 

  def total_price
    line_items.to_a.sum {|item| item.total_price }
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :product_id, :text
  belongs_to :product  

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base

  belongs_to :order
  belongs_to :product
  belongs_to :cart
  attr_accessible :cart_id, :product_id
  attr_accessible :product
  attr_accessible :quantity

  def total_price
    product.price * quantity
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :address, :email, :name, :pay_type, :time
  attr_accessible :cart, :product
  has_many :line_items, :dependent => :destroy
  PAYMENT_TYPES = [ "Check", "Credit card" , "Purchase order" ]
  validates :name, :address, :email, :pay_type, :presence => true
  validates :pay_type, :inclusion => PAYMENT_TYPES
  
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def total_price
    line_items.to_a.sum {|item| item.total_price }
  end
  
  def modify_product_stock_volumes(cart)
    cart.line_items.each do |item|
      #Product.find_by_title(item.title).stock_volumes -= item.quantity
      
    #  product = Product.find(:all,
     #   :conditions => " id = 'item.product_id'")
      if item 
        product = Product.find(item.product_id)
        product.stock_volumes -= item.quantity
        product.save
      end
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :comments  
  has_many :orders, :through => :line_items

  before_destroy :ensure_not_referenced_by_any_line_item
  
  attr_accessible :description, :image_url, :price, :title, :stock_volumes, :tags
  BOOK_TYPES = [ "IT", "math" ,"subclass11","subclass12","subclass13","subclass14",
                "subclass21","subclass22","subclass23","subclass24","subclass25",
                "subclass31","subclass32","subclass33","subclass34","subclass35",
                "subclass41","subclass42","subclass43","subclass44","subclass45"]
  validates :title, :description, :image_url, :stock_volumes, :tags, presence: true
  validates :tags, :inclusion => BOOK_TYPES
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)$}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }
  private
	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
			return true
		else
			errors.add(:base, 'Line Items present')
			return false
		end
	end
end

app/models/subclass.rb
class Subclass < ActiveRecord::Base
  attr_accessible :content, :type_id  
  belongs_to :type
end

app/models/type.rb
class Type < ActiveRecord::Base
  attr_accessible :type_name, :content
  has_many :subclasses
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password_digest, :password, :password_confirmation
  validate :name, presence: true, uniqueness: true
  has_secure_password
  after_destroy :ensure_an_admin_remains
  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  #before_filter :authorize
  def index
    @total_orders = Order.count
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_filter :authorize, only: [:show, :search]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  def who_bought 
    @product = Product.find(params[:id])
    respond_to do |format|
      format.atom
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  #search/IT
  def search
    #@product = Product.find(:all ,tags:  '#{tags}' )
    #@product = Product.where(:tags => params[:tags])
    #@products = Product.find(:all ,:conditions => ["title = ?", params[:title]])
    @products = Product.find(:all ,:conditions => ["tags = ?", params[:tags]])
  end 
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def hidden_div_if(condition, attributes={}, &block)
    if condition
      attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)

  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/subclass_helper.rb
module SubclassHelper
end

app/helpers/subclasses_helper.rb
module SubclassesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, rows:6 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :stock_volumes%><br />
    <%= f.text_field :stock_volumes %>
  </div>
  <div class="field">
    <%= f.label :tags%><br />
    <%= f.select :tags, Product::BOOK_TYPES %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%= stylesheet_link_tag    "products" %> <!--#:media => "all"-->
<%= javascript_include_tag "products" %>
<%= csrf_meta_tags %>
<h1>Listing products</h1>

<table>
  <% @products.each do |product| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <td>
        <%= image_tag(product.image_url, class: 'list_image') %>
      </td>
      <td class="list_description">
        <dl>
          <dt><%= product.title %></dt>
          <dd><%= truncate(strip_tags(product.description),
                length: 80) %></dd>
          <dd>stock volumes:<%= product.stock_volumes %></dd>
        </dl>
      </td>
      <td class="list_actions">
        <%= link_to 'Show', product %><br/>
        <%= link_to 'Edit', edit_product_path(product) %><br/>
        <%= link_to 'Destroy', product,
                    confirm: 'Are you sure?',
                    method: :delete %>
      </td>
    </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/search.html.erb
<%= stylesheet_link_tag    "search" %>
<%= javascript_include_tag "search" %>
<%= csrf_meta_tags %>
<% if notice %>
<p id="notice"><%= notice%></p>
<% end %>
<% if @products.first %>
<h1><%= @products.first.tags %> Books</h1>

<% @products.each do |product| %>
	<div class="entry">
		<%= image_tag(product.image_url) %>
		<h3><%= product.title %></h3>
		<%= sanitize(product.description)%>
		<div class="price_line">
			<span class="price"><%= number_to_currency(product.price) %></span>
			<%= button_to 'Add to Cart', line_items_path(product_id: product),
				remote: true %>
			<%= link_to 'comment', product %>
		</div>	

	</div>
<% end %>
<% else %>
<p id="no">Sorry ! No Books available.</p>
<%= link_to 'back', store_path %>
<% end %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @product.title %>
</p>

<p>
  <b>Description:</b>
  <%= sanitize(@product.description) %>
  
</p>

<p>
  <b>Image url:</b>
  <%= @product.image_url %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>
<p>
  <b>Stock volumes:</b>
  <%= @product.stock_volumes %>
</p>
<p>
  <b>Tag:</b>
  <%= @product.tags %>
</p>


<h2>Comments</h2>  
  
<% @product.comments.each do |comment| %>  
  <p><%= comment.text %></p>  
  <p><%= comment.created_at.localtime %></p>

<!-- 
  <p><%= link_to "Delete Comment", [@product, comment], :method => :delete, :confirm => "Are you sure?" %></p>  
-->
  <p>---------------------------------------------------------------------------------------------------------</p>
<% end %>  
  
<%= form_for [@product,@product.comments.build] do |f| %>  
  <p><%= f.text_area :text, :size => '40x10' %> </p>  
  <p><%= f.submit "Make Comment" %> </p>  
<% end %>






<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>