config/routes.rb
Depot::Application.routes.draw do

  get "subclasses/create"

  get "subclasses/destroy"


  resources :types do  
    resources :subclasses  
  end  

  get "comments/create"

  get "comments/destroy"

  get 'admin' => 'admin#index'

  #get 'search'=> 'products#search'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :products do
    get 'search' => :search
  end

  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products do
	  resources :comments  

      get :who_bought, :on => :member
    end
    get 'search'=> 'products#search'
    root :to => 'store#index', :as => 'store'

  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body

  attr_accessible :order
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    
	  if current_item
      current_item.quantity += 1

	  else
		  current_item = line_items.build(product_id: product_id)
	  end 
	  current_item
  end 

  def total_price
    line_items.to_a.sum {|item| item.total_price }
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :product_id, :text
  belongs_to :product  

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base

  belongs_to :order
  belongs_to :product
  belongs_to :cart
  attr_accessible :cart_id, :product_id
  attr_accessible :product
  attr_accessible :quantity

  def total_price
    product.price * quantity
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :address, :email, :name, :pay_type, :time
  attr_accessible :cart, :product
  has_many :line_items, :dependent => :destroy
  PAYMENT_TYPES = [ "Check", "Credit card" , "Purchase order" ]
  validates :name, :address, :email, :pay_type, :presence => true
  validates :pay_type, :inclusion => PAYMENT_TYPES
  
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def total_price
    line_items.to_a.sum {|item| item.total_price }
  end
  
  def modify_product_stock_volumes(cart)
    cart.line_items.each do |item|
      #Product.find_by_title(item.title).stock_volumes -= item.quantity
      
    #  product = Product.find(:all,
     #   :conditions => " id = 'item.product_id'")
      if item 
        product = Product.find(item.product_id)
        product.stock_volumes -= item.quantity
        product.save
      end
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :comments  
  has_many :orders, :through => :line_items

  before_destroy :ensure_not_referenced_by_any_line_item
  
  attr_accessible :description, :image_url, :price, :title, :stock_volumes, :tags
  BOOK_TYPES = [ "IT", "math" ,"subclass11","subclass12","subclass13","subclass14",
                "subclass21","subclass22","subclass23","subclass24","subclass25",
                "subclass31","subclass32","subclass33","subclass34","subclass35",
                "subclass41","subclass42","subclass43","subclass44","subclass45"]
  validates :title, :description, :image_url, :stock_volumes, :tags, presence: true
  validates :tags, :inclusion => BOOK_TYPES
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)$}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }
  private
	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
			return true
		else
			errors.add(:base, 'Line Items present')
			return false
		end
	end
end

app/models/subclass.rb
class Subclass < ActiveRecord::Base
  attr_accessible :content, :type_id  
  belongs_to :type
end

app/models/type.rb
class Type < ActiveRecord::Base
  attr_accessible :type_name, :content
  has_many :subclasses
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password_digest, :password, :password_confirmation
  validate :name, presence: true, uniqueness: true
  has_secure_password
  after_destroy :ensure_an_admin_remains
  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/subclass_helper.rb
module SubclassHelper
end

app/helpers/subclasses_helper.rb
module SubclassesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>
It's <%= Time.now %>
We have <%= pluralize(@total_orders, "order") %>.

app/views/layouts/_form.html.erb
<%= form_for(Product) do |f| %>
  

 

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
  <%= stylesheet_link_tag    "application" %> <!--#:media => "all"-->
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
	<div id="banner">
		<%= form_tag store_path, :class => 'locale' do %>
        <%= select_tag 'set_locale',
          options_for_select(LANGUAGES, I18n.locale.to_s),
          :onchange => 'this.form.submit()' %>
        <%= submit_tag 'submit' %>
        <%= javascript_tag "$('.locale input').hide()" %>
        <% end %>
		<%= image_tag("logo.png")%>
		<%= @page_title || t('.title') %>
		<div id="sign">
			<% if session[:user_id] %>
				<%= User.find(session[:user_id]).name %>
				<%= link_to 'Logout' , logout_path, method: :delete %>
			<% else %>
			<div id="signu"><%= link_to 'Sign Up',new_user_path%></div>
			<div id="signi"><%= link_to 'Sign In',login_path%></div>
		<% end %>
		</div>
	</div>
	<div id="columns">
		<div id="side">
			<div id="cart">	
			<% if @cart %>	
			<%= hidden_div_if(@cart.line_items.empty? ,id: 'cart') do%>
				<%= render @cart %>	
			<% end %>
			<% end %>			
			</div>

			<br />
			<form action="/search" method="get">  
			<div class="field">
    			<label class="tag">Book Tag</label><br />
    			<input type="text" name="tags" />
    			<br />
    			<br />
				<input type="submit" value="search" />
  			</div>

			</form>


			<ul>
				<li><%= link_to 'Home Page', store_path %></li>
                <li><a href="http://www..../faq" ><%= t('.questions') %></a></li>
                <li><a href="http://www..../news" ><%= t('.news') %></a></li>
                <li><a href="http://www..../contact" ><%= t('.contact') %></a></li>
			</ul>
			
			<% if session[:user_id] %>
				<ul>
					
					<li><%= link_to 'Orders' , orders_path %></li>
					<li><%= link_to 'Products', products_path %></li>
					<li><%= link_to 'Users', users_path %></li>		
				</ul>
			
			<% end %>
			<br>
			<br>
			<div class="type">
			<h3>BOOK TYPES</h3>

			<table>
			  <tr>
			    
			    <th></th>
			    <th></th>
			    <th></th>
			  </tr>
			<% @type = Type.all%>
			<% if @type %>
			<% @type.each do |type| %>
			  <tr>
			    <td>[<%= type.type_name %>]
			    
			    	<br>
				    <form action="/search" method="get">
				    	<select name="tags">
				    		<% type.subclasses.each do |subclass| %>
				    		<option value = "<%= subclass.content%>" ><%= subclass.content%></option>
				    		<% end %>
				    		<br />
				    		<br />
				    		 <input type="submit" value="search" />
				    	</select>
				    	
				    </form>		
				</td>
			<!--    <td><%= link_to 'Show', type %></td>
			    <td><%= link_to 'Edit', edit_type_path(type) %></td>
			    <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
			  </tr>
			<% end %>
			<%end%>
			</table>
			<br />
		<!--	<%= link_to 'New Type', new_type_path %>	-->
		</div>
		</div>
		<div id="main">
			<%= yield %>
		</div>
	</div>

</body>
</html>

app/views/order_notifier/received.text.erb
OrderNotifier#received

<%= @greeting %>, find me in app/views/app/views/order_notifier/received.text.erb

Dear <%= @order.name %>

Thank you for your recent order from The Pragmatic Store.

You ordered the following items:

<%= render @order.line_items %>

We'll send you a separate e-mail when your order ships.

app/views/order_notifier/shipped.html.erb
<h3>Pragmatic Order Shipped </h3>
<p>
	This is just to let you know that we've shipped your recent order:
</p>
<table>
	<tr><th colspan= "2" >Qty </th><th>Description </th></tr>
<%= render @order.line_items %>
</table>

app/views/order_notifier/shipped.text.erb
OrderNotifier#shipped

<%= @greeting %>, find me in app/views/app/views/order_notifier/shipped.text.erb